theme: jekyll-theme-slate
title: John J. Berroa
email: johnberroa@gmail.com
author: John Berroa
description: A website detailing my projects and journey through the world of data science and neural inspired algorithms.
